package rules

var sourceName map[string]string = map[string]string{
	"stormwrack":                            "Stormwrack",
	"fiendish_codex_i:_hordes_of_the_abyss": "Fiendish Codex 1: Hordes of the Abyss",
	"power_of_faerun":                       "Power of Faerun",
	"player's_handbook_3.0":                 "Player's Handbook 3.0",
	"draconomicon":                          "Draconomicon",
	"eberron_campaign_setting":              "Eberron Campaign Setting",
	"races_of_destiny":                      "Races of destiny",
	"silver_marches":                        "Silver Marches",
	"lords_of_darkness":                     "Lords of Darkness",
	"races_of_faerun":                       "Races of Faerun",
	"book_of_vile_darkness":                 "Book of Vile Darkness",
	"book_of_exalted_deeds":                 "Book of Exalted Deeds",
	"weapons_of_legacy":                     "Weapons of Legacy",
	"faiths_of_eberron":                     "Faiths of Eberron",
	"complete_divine":                       "Complete Divine",
	"races_of_eberron":                      "Races of Eberron",
	"libris_mortis:_the_book_of_the_dead":   "Libris Mortis: The Book of the Dead",
	"stronghold_builder's_guidebook":        "Stronghold Builder's Guidebook",
	"enemies_and_allies":                    "Enemies and Allies",
	"complete_champion":                     "Complete Champion",
	"frostburn":                             "Frostburn",
	"sharn:_city_of_towers":                 "Sharn: City of Towers",
	"miniatures_handbook":                   "Miniatures Handbook",
	"manual_of_the_planes":                  "Manual of the Planes",
	"sandstorm":                             "Sandstorm",
	"races_of_stone":                        "Races of Stone",
	"defenders_of_the_faith:_a_guidebook_to_clerics_and_paladins": "Defenders of the Faith: A Guidebook to Clerics and Paladins",
	"lost_empires_of_faerun":                       "Lost Empires of Faerun",
	"forgotten_realms_campaign_setting":            "Forgotten Realms Campaign Setting",
	"complete_mage":                                "Complete Mage",
	"savage_species":                               "Savage Species",
	"races_of_the_wild":                            "Races of the Wild",
	"unapproachable_east":                          "Unapproachable East",
	"expanded_psionics_handbook":                   "Expanded Psionics Handbook",
	"dragon_magic":                                 "Dragon Magic",
	"the_forge_of_war":                             "The Forge of War",
	"heroes_of_horror":                             "Feroes of Forror",
	"underdark":                                    "Underdark",
	"complete_adventurer":                          "Complete Adventurer",
	"fiendish_codex_ii:_tyrants_of_the_nine_hells": "Fiendish Codex 2: Tyrants of the Nine Hells",
	"magic_of_faerun":                              "Magic of Faerun",
	"champions_of_ruin":                            "Champions of Ruin",
	"complete_scoundrel":                           "Complete Scoundrel",
	"cityscape":                                    "Cityscape",
	"masters_of_the_wild:_a_guidebook_to_barbarians,_druids,_and_rangers": "Masters of the Wild: A guidebook to Barbarians, Druids, and Rangers",
	"dragonmarked":            "Dragonmarked",
	"monster_manual_iv":       "Monster Manual 4",
	"magic_of_eberron":        "Magic of Eberron",
	"ghostwalk":               "Ghostwalk",
	"complete_arcane":         "Complete Arcane",
	"dragons_of_faerun":       "Dragons of Faerun",
	"complete_warrior":        "Complete Warrior",
	"champions_of_valor":      "Champions of Valor",
	"player's_handbook_v.3.5": "Player's Handbook 3.5",
	"player's_handbook_ii":    "Player's Handbook 2",
	"epic_level_handbook":     "Epic Level Handbook",
	"tome_and_blood:_a_guidebook_to_wizards_and_sorcerers": "Tome and Blood: A Guidebook to Wizards and Sorcerers",
	"spell_compendium": "Spell Compendium",
	"song_and_silence:_a_guidebook_to_bards_and_rogues": "Song and Silence: A Guidebook to Bards and Rogues",
	"magic_of_incarnum":            "Magic of Incarnum",
	"shining_south":                "Shining South",
	"secrets_of_sarlona":           "Secrets of Sarlona",
	"psionics_handbook_3.0":        "Psionics Handbook 3.0",
	"drow_of_the_underdark":        "Drow of the Underdark",
	"lords_of_madness":             "Lords of Madness",
	"city_of_splendors:_waterdeep": "City of Splendors: Waterdeep",
	"races_of_the_dragon":          "Races of the Dragon",
	"heroes_of_battle":             "Heroes of Battle",
	"tome_of_magic":                "Tome of Magic",
	"planar_handbook":              "Planar Handbook",
	"serpent_kingdoms":             "Serpent Kingdoms",
	"oriental_adventures":          "Oriental Adventures",
}
